/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-09-18 10:14:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>UserRegister</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   label{\r\n");
      out.write("  width: 175px;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"text-align:center\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headers.jsp", out, false);
      out.write('\r');
      out.write('\n');

String message = request.getParameter("message");
if (message != null){
	out.println("<font color='red'>" + message + "</font>");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function register() {\r\n");
      out.write("    \r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("    var name = document.getElementById(\"name\").value;\r\n");
      out.write("    var mobileno = document.getElementById(\"mobileno\").value;\r\n");
      out.write("    var password = document.getElementById(\"password\").value;\r\n");
      out.write("    var address = document.getElementById(\"address\").value;\r\n");
      out.write("    var formData = \"name=\"+name+ \"&mobileno=\" + mobileno + \"&password=\" + password+ \"&address=\"+address;\r\n");
      out.write("    console.log(formData);\r\n");
      out.write("\r\n");
      out.write("    var url = \"http://localhost:8080/waterplant_web/RegisterServlet?\" + formData;\r\n");
      out.write("    console.log(url);\r\n");
      out.write("    var formData = {};\r\n");
      out.write("    $.get(url, function(response) {\r\n");
      out.write("        console.log(response);\r\n");
      out.write("\r\n");
      out.write("        var msg=JSON.parse(response);\r\n");
      out.write("      \r\n");
      out.write("        if (msg.errorMessage!=null) {\r\n");
      out.write("            \r\n");
      out.write("            window.location.href = \"userregister.jsp\";\r\n");
      out.write("        } else {\r\n");
      out.write("            alert(\" Registered Successfully\");\r\n");
      out.write("            window.location.href = \"userlogin.jsp\";\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("<br/><h3>USER REGISTER</h3><br/>\r\n");
      out.write("\r\n");
      out.write("<form onsubmit=\"register()\">\r\n");
      out.write("<label>NAME:</label>\r\n");
      out.write("<input type=\"text\" name=\"name\" id=\"name\" size=20 placeholder=\"Enter Name\" required autofocus/>\r\n");
      out.write("<br/></br>\r\n");
      out.write("\r\n");
      out.write("<label>MOBILE_NUMBER:</label>\r\n");
      out.write("<input type=\"number\" name=\"mobileno\" id=\"mobileno\" size=25 placeholder=\"Enter Mobile No\" required />\r\n");
      out.write("<br/></br>\r\n");
      out.write("\r\n");
      out.write("<label>PASSWORD:</label>\r\n");
      out.write("<!--<input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Enter Password\" required />  -->\r\n");
      out.write("<input type=\"password\" name=\"password\" id=\"password\" size=20 placeholder=\"Enter Password\" required\r\n");
      out.write(" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\" \r\n");
      out.write(" title=\"Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters required \"/>\r\n");
      out.write("<br/></br>\r\n");
      out.write("<label>ADDRESS:</label>\r\n");
      out.write("<input type=\"text\" name=\"address\" id=\"address\" size=20 placeholder=\"Enter Address\" required />\r\n");
      out.write("<br/></br><br/>\r\n");
      out.write("<input type=\"submit\" value=\"Submit\" class=\"btn btn-success\">\r\n");
      out.write("<button type=\"reset\" class=\"btn btn-danger\" value=\"clear\">clear</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
